# This is a basic workflow to help you get started with Actions

name: Build, Release app to Github Pages and Firebase Hosting
# name: Test, Build and Release apk
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          #        flutter-version: '1.19.0-5.0.pre'
          channel: 'dev'
      - name: 'Run flutter pub get'
        run: flutter pub get
      #    - name: 'Run Test(s)'
      #      run: flutter test
      - name: Enable flutter web
        run: flutter config --enable-web
      - name: 'Build Web App'
        run: flutter build web
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./build/web
#      - name: Deploy to Firebase Hosting
#        uses: w9jds/firebase-action@master
#        with:
#          args: deploy --only hosting
#        env:
#          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}